version: '3'
services:
  backend:
    image: task-manager-flask
    ports:
      - "5000:5000"
    deploy:
      mode: global
  myapp:
    image: task-manager-flask
    ports:
      - "5000:5001"
    deploy:
      mode: global
