version: '3'
services:
  backend:
    image: python:3.9  # Используем официальный образ Python
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    working_dir: /devops
    command: python app.py  # Команда для запуска приложения
    ports:
      - "5000:5000"  # Проксирование порта из контейнера на хост
    volumes:
      - .:/devops  # Монтируем текущий каталог в контейнер
  backend-2:
    image: python:3.9  # Используем официальный образ Python
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    working_dir: /devops
    command: python app.py  # Команда для запуска приложения
    ports:
      - "5001:5000"  # Проксирование порта из контейнера на хост
    volumes:
      - .:/devops  # Монтируем текущий каталог в контейнер
